apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-synapse"
spec:
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      serviceAccountName: "{{ .Release.Name }}-synapse"
      containers:
        - name: synapse
          image: asyncy/platform-synapse:v0.1.7-3-g7cd3326
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POSTGRES
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser-url
            - name: IN_CLUSTER
              value: "true"
          resources:
            limits:
              memory: 72M
            requests:
              memory: 72M
