apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-synapse"
  labels:
    app: synapse
spec:
  selector:
    app: synapse
  ports:
    - port: 80
      name: main
      protocol: TCP
      targetPort: 8080
