apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-tls-cert"
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A .Values.tls.fullchain is required" .Values.tls.fullchain | b64enc }}
  tls.key: {{ required "A .Values.tls.privkey is required" .Values.tls.privkey | b64enc }}
