dependencies:

# database
- name: postgresql
  version: 6.3.9
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: postgresql.enabled

- name: nginx-ingress
  version: 1.26.2
  repository: https://kubernetes-charts.storage.googleapis.com
