dependencies:

# database
- name: postgresql
  version: 6.3.9
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: postgresql.create

- name: traefik
  version: 1.85.1
  repository: https://kubernetes-charts.storage.googleapis.com
