apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: storyscript/auth
      context: ../auth/
    - image: storyscript/creds
      context: ../creds/
    - image: storyscript/database
      context: ../database/
    - image: storyscript/geh
      context: ../geh/
    - image: storyscript/graphql
      context: ../graphql/
    - image: storyscript/http
      context: ../http/
    - image: storyscript/language
      context: ../language/
    - image: storyscript/router
      context: ../router/
    - image: storyscript/runtime
      context: ../runtime/
    - image: storyscript/sls
      context: ../sls/
    - image: storyscript/studio
      context: ../studio/
      docker:
        dockerfile: ./.docker/Dockerfile.docker
    - image: storyscript/worker
      context: ../worker/
deploy:
  helm:
    releases:
      - name: storyscript
        chartPath: ./
        imageStrategy:
          # our image values use the helm convention
          # i.e. image: { repository, tag }
          helm: {}
        values:
          # skaffold will update these image values (using imageStrategy)
          # to match those generated during the build step
          auth.image: storyscript/auth
          creds.image: storyscript/creds
          schema.image: storyscript/database
          geh.image: storyscript/geh
          graphql.image: storyscript/graphql
          http.image: storyscript/http
          compiler.image: storyscript/language
          router.image: storyscript/router
          runtime.image: storyscript/runtime
          sls.image: storyscript/sls
          studio.image: storyscript/studio
          worker.image: storyscript/worker
        valuesFiles:
          - ./values.env.yaml
