postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 9.6.14
  persistence:
    enabled: true
    mountPath: /data
  # dataDir cannot be the mountPath,
  # it has to be a subdirectory
  postgresqlDataDir: /data/pgdata
  postgresqlDatabase: storyscript
  postgresqlUsername: storyscript
  postgresqlPassword: storyscript
