apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-scheduler"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-scheduler"
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
