apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-runtime"
type: Opaque
data:
  wolfram_app_id: {{ required "A .Values.runtime.wolfram_app_id is required" .Values.runtime.wolfram_app_id | b64enc }}
  github_app_id: {{ required "A .Values.runtime.github.app_id is required" .Values.runtime.github_app.id | b64enc }}
  github_app_private_Key: {{ required "A .Values.runtime.github.app_private_key is required" .Values.runtime.github_app.private_key | b64enc }}
