apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-language"
  labels:
    app: language
spec:
  selector:
    app: language
  ports:
    - port: 80
      name: external
      protocol: TCP
      targetPort: 5001
