apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-gateway"
  labels:
    app: gateway
  annotations:
    traefik.ingress.kubernetes.io/priority: "1"
spec:
  rules:
  - host: "*.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-gateway"
          servicePort: 8888
