apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-gateway"
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8888
      name: external
      protocol: TCP
      targetPort: 8888
    - port: 8889
      name: internal
      protocol: TCP
      targetPort: 8889
