apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-gateway"
  labels:
    app: gateway
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: "{{ .Release.Name }}-gateway"
            servicePort: 8888
