apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-http"
spec:
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http
          image: {{ include "storyscript.image" .Values.http.image }}
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser
            - name: RUNTIME_URL
              value: {{ printf "http://%s-runtime.%s.svc.cluster.local:9001" .Release.Name .Release.Namespace }}
