apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-database-credentials"
type: Opaque
data:
  # type: libpq connection string
  superuser: {{ include "storyscript.databaseUrl" (merge (dict "superuser" true) .) | b64enc }}
  # type: asyncpg connection string (accepts query parameters)
  superuser-search_path: {{ include "storyscript.databaseUrl" (merge (dict "superuser" true "search_path" true) .) | b64enc }}
  # type: perl URI::db connection string
  superuser-sqitch: {{ include "storyscript.databaseUrl" (merge (dict "superuser" true "sqitch" true) .) | b64enc }}
  # type: libpq connection string
  public: {{ include "storyscript.databaseUrl" . | b64enc }}
  # type: database-init-job argument
  public-pgoptions: {{ printf "-c storyscript.graphql_authenticator_username=%s -c storyscript.graphql_authenticator_password=%s" .Values.graphql.postgresqlUsername .Values.graphql.postgresqlPassword | b64enc }}
