apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-schema-apply"
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-schema-apply"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: schema-apply-job
          image: "{{ .Values.schema.image }}"
          env:
            - name: PGOPTIONS
              # used to create graphql authenticator role
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: public-pgoptions
            - name: DATABASE_URL
              # used to connect to database
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser-sqitch
