apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-database-credentials"
type: Opaque
data:
  superuser-url: {{ include "storyscript.databaseUrl" . }}
  public-role: .Values.publicRole
  public-password: .Values.publicPassword
