apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-database-credentials"
type: Opaque
data:
  sqitch-url: {{ include "storyscript.sqitchUrl" . | b64enc | quote }}
  superuser-url: {{ include "storyscript.superuserUrl" . | b64enc | quote }}
  public-url: {{ include "storyscript.publicUrl" . | b64enc | quote }}
