apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-database-credentials"
type: Opaque
data:
  sqitch-url: {{ include "storyscript.databaseUrl" (merge (dict "sqitch" true "superuser" true) .) | b64enc | quote }}
  superuser-url: {{ include "storyscript.databaseUrl" (merge (dict "superuser" true) .) | b64enc | quote }}
  public-url: {{ include "storyscript.databaseUrl" . | b64enc | quote }}
