apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-sls"
  labels:
    app: sls
spec:
  tls:
  - hosts:
     - "sls.{{ .Values.domain }}"
  rules:
  - host: "sls.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-sls"
          servicePort: 2042
