apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-router"
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          image: "{{ .Values.router.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: HTTP_SERVICE_URL
              value: {{ printf "%s-http.%s.svc.cluster.local:9000" .Release.Name .Release.Namespace }}
            - name: DATABASE_URL
              # used to connect to db
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser-search_path
