apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-nlp"
  labels:
    app: nlp
spec:
  selector:
    app: nlp
  ports:
    - port: 80
      name: external
      protocol: TCP
      targetPort: 8000
