apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-nlp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp
  template:
    metadata:
      labels:
        app: nlp
    spec:
      containers:
        - name: nlp
          image: {{ include "storyscript.image" .Values.nlp.image }}
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8000
