apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-studio"
  labels:
    app: studio
spec:
  tls:
  - hosts:
     - "studio.{{ .Values.domain }}"
  rules:
  - host: "studio.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-studio"
          servicePort: 4000
