apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-studio"
  labels:
    app: studio
spec:
  selector:
    app: studio
  ports:
    - port: 4000
      name: external
      protocol: TCP
      targetPort: 80
