apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-proxy"
  labels:
    app: proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-alias: "www.{{ .Values.domain }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.domain }}"
    - "www.{{ .Values.domain }}"
    secretName: "{{ .Release.Name }}-tls-cert"
  {{- end }}
  rules:
  - host: "{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-proxy"
          servicePort: 80
