apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-proxy"
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  type: LoadBalancer
  ports:
  - port: 80
    name: external
    protocol: TCP
    targetPort: 80
