apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-proxy-conf"
data:
  nginx.conf: |
    user nginx;
    events {
    }
    http {
      upstream landing {
        server storyscript.netlify.com:443;
      }

      upstream studio {
        server studio.{{ .Values.domain }}:443;
      }

      server {
        listen 80 default_server;
        server_name {{ .Values.domain }} www.{{ .Values.domain }};

        location = / {
            proxy_set_header Host {{ .Values.domain }};
            proxy_pass https://landing;
            proxy_cache_revalidate on;
        }

        location / {
            try_files $uri @static_landing;
        }

        location @static_landing {
            proxy_set_header Host {{ .Values.domain }};
            proxy_pass https://landing$uri;

            proxy_intercept_errors on;
            recursive_error_pages on;
            error_page 404 = @static_studio;
        }

        location @static_studio {
            proxy_set_header Host studio.{{ .Values.domain }};
            proxy_pass https://studio$uri;
        }
      }
    }
