apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-auth"
  labels:
    app: auth
  annotations:
    ingress.kubernetes.io/protocol: "https"
spec:
  tls:
  - hosts:
     - "auth.{{ .Values.domain }}"
  rules:
  - host: "auth.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-auth"
          servicePort: 3000
